- name: Create .kube diretory
  ansible.builtin.file:
    path: /home/{{ ansible_user }}/.kube
    state: directory

- name: Uncompress helm
  ansible.builtin.unarchive:
    src: https://get.helm.sh/helm-v3.6.0-linux-amd64.tar.gz
    dest: /tmp
    remote_src: yes

- name: Copy helm to /usr/local/bin/helm
  become: true
  ansible.builtin.copy:
    src: /tmp/linux-amd64/helm
    dest: /usr/local/bin/helm
    mode: "0755"
    remote_src: yes

- name: Remove unarchived helm directory
  ansible.builtin.file:
    path: /tmp/linux-amd64
    state: absent

- name: Install pip files
  ansible.builtin.pip:
    name:
      - PyYAML
