---
- name: Update apt repository cache
  become: true
  apt:
    update_cache: yes

- name: Install packages
  become: true
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - apt-transport-https
    - ca-certificates
    - chrony
    - curl
    - software-properties-common
    - net-tools
    - nfs-utils
    - bash-completion
    - git
    - vim

- name: Set vim as default editor
  become: true
  alternatives:
    name: editor
    path: /usr/bin/vim.basic

# ansible-galaxy collection install community.general
- name: Set timezone to Europe/Madrid
  become: true
  community.general.timezone:
    name: Europe/Madrid

- name: Enable Chrony service
  become: true
  systemd:
    name: chrony
    enabled: yes

- name: Ensure Chrony service is running
  become: true
  systemd:
    name: chrony
    state: started