---
- name: Correct python version selected
  become: true
  community.general.alternatives:
    name: python
    link: /usr/bin/python
    path: /usr/bin/python3

- name: Update apt repository cache
  become: true
  apt:
    update_cache: yes

- name: Install Common packages
  become: true
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - apt-transport-https
    - bash-completion
    - ca-certificates
    - chrony
    - curl
    - git
    - net-tools
    - nfs-common
    - python3-pip
    - software-properties-common
    - vim

- name: Set vim as default editor
  become: true
  alternatives:
    name: editor
    path: /usr/bin/vim.basic

- name: Set timezone to Europe/Madrid
  become: true
  community.general.timezone:
    name: Europe/Madrid

- name: Enable Chrony service
  become: true
  systemd:
    name: chrony
    enabled: yes

- name: Ensure Chrony service is running
  become: true
  systemd:
    name: chrony
    state: started