- name: Remove ingress-nginx
  community.kubernetes.helm:
    name: controller
    chart_ref: ingress-nginx/ingress-nginx
    release_namespace: default
    values: "{{ lookup('template', 'values.yaml.j2') | from_yaml }}"
    state: absent

- name: Remove ingress-nginx repository
  community.kubernetes.helm_repository:
    name: ingress-nginx
    repo_url: "https://kubernetes.github.io/ingress-nginx"
    repo_state: absent
