# Copy rbac.yaml
- name: Copy rbac.yaml to /tmp/rbac.yaml
  ansible.builtin.copy:
    src: rbac.yaml
    dest: /tmp/rbac.yaml

# Init Kubernetes master
- name: Init K8s
  become: true
  ansible.builtin.shell:
    # cmd: kubeadm init --apiserver-advertise-address="{{ control_plane_endpoint }}" --node-name="master.k8smvilla.com" --pod-network-cidr="{{ pod_network_cidr }}"
    cmd: kubeadm init --node-name="master.k8smvilla.com" --pod-network-cidr="{{ pod_network_cidr }}"

# Create $HOME/.kube directory for copying kubernetes config file
- name: Create .kube directory
  become: true
  ansible.builtin.file:
    path: /home/{{ ansible_user }}/.kube
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    state: directory

# Copy /etc/kubernetes/admin.conf to $HOME/.kube/config to use kubernetes
- name: Copy k8s config
  become: true
  ansible.builtin.copy:
    src: /etc/kubernetes/admin.conf
    dest: /home/{{ ansible_user }}/.kube/config
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0600"
    remote_src: yes

- name: Copy k8s config to local .kube directory
  become: true
  ansible.builtin.fetch:
    src: /etc/kubernetes/admin.conf
    dest: /root/.kube/config
    flat: yes

- name: Get Join command
  ansible.builtin.shell:
    cmd: kubeadm token create --print-join-command
  register: k8sjc

- name: Register Join command
  ansible.builtin.set_fact:
    kubernetes_join_command: "{{ k8sjc.stdout }}"

- name: Debug join command
  ansible.builtin.debug:
    var: k8sjc.stdout

- name: Download kube-flannel manifest
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
    dest: /tmp/kube-flannel.yml
    mode: '0664'

- name: Apply flannel manifest to the cluster
  community.kubernetes.k8s:
    state: present
    src: /tmp/kube-flannel.yml

- name: Apply RBAC
  community.kubernetes.k8s:
    state: present
    src: /tmp/rbac.yaml

- name: Remove kube-flannel.yml manifest
  ansible.builtin.file:
    path: /tmp/kube-flannel.yml
    state: absent

- name: Remove RBAC
  ansible.builtin.file:
    path: /tmp/rbac.yaml
    state: absent

- name: Create clusterrolebinding
  ansible.builtin.shell:
    cmd: kubectl create clusterrolebinding kubernetes-dashboard --clusterrole=cluster-admin --serviceaccount=kube-system:kubernetes-dashboard