# Init Kubernetes master
- name: Init K8s
  become: true
  ansible.builtin.shell:
    cmd: kubeadm init --apiserver-advertise-address="{{ control_plane_endpoint }}" --node-name="master.k8smvilla.com" --pod-network-cidr="{{ pod_network_cidr }}" --ignore-preflight-errors="all"

# Create $HOME/.kube directory for copying kubernetes config file
- name: Create .kube directory
  become: true
  ansible.builtin.file:
    path: /home/{{ ansible_user }}/.kube
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    state: directory

# Copy /etc/kubernetes/admin.conf to $HOME/.kube/config to use kubernetes
- name: Copy k8s config
  become: true
  ansible.builtin.copy:
    src: /etc/kubernetes/admin.conf
    dest: /home/{{ ansible_user }}/.kube/config
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0600"
    remote_src: yes

- name: Copy k8s config to local .kube directory
  become: true
  ansible.builtin.fetch:
    src: /etc/kubernetes/admin.conf
    dest: /root/.kube/config
    flat: yes
- name: Install Calico
  ansible.builtin.shell:
    cmd: kubectl apply -f https://docs.projectcalico.org/v3.3/getting-started/kubernetes/installation/hosted/rbac-kdd.yaml

- name: Apply Calico manifest
  shell: kubectl apply -f https://docs.projectcalico.org/manifests/calico.yaml

- name: Get Join command
  ansible.builtin.shell:
    cmd: kubeadm token create --print-join-command
  register: k8sjc

- name: Register Join command
  ansible.builtin.set_fact:
    kubernetes_join_command: "{{ k8sjc.stdout }}"

- name: Debug join command
  ansible.builtin.debug:
    var: k8sjc.stdout
