- include_tasks: create.yml
  when: action_mode == 'create'

- include_tasks: get_cluster_info.yml
  when: action_mode == 'get_cluster_info'

- include_tasks: destroy.yml
  when: action_mode == 'destroy' and hostvars['Master']['kubernetes_masters']
