# Check if docker-ce is installed
- name: Gather the package facts
  ansible.builtin.package_facts:
    manager: apt
  async: 10
  poll: 2

- name: Ensure Docker service is stopped
  become: true
  ansible.builtin.systemd:
    name: docker
    state: stopped
  async: 300
  poll: 5
  when: "'docker-ce' in ansible_facts.packages"

- name: Disable Docker service
  become: true
  ansible.builtin.systemd:
    name: docker
    enabled: no
  async: 10
  poll: 2
  when: "'docker-ce' in ansible_facts.packages"

- name: Uninstall Docker
  become: true
  ansible.builtin.apt:
    name: docker-ce
    purge: yes
    state: absent
  register: docker_removal
  when: "'docker-ce' in ansible_facts.packages"

- name: Remove /var/lib/docker
  become: true
  ansible.builtin.file:
    path: /var/lib/docker
    state: absent
  async: 30
  poll: 5
  when: docker_removal.changed
