---
#- hosts: all
#  gather_facts: true
#  #become: true
#  tasks:
#  - name: Cat hostname
#    ansible.builtin.shell:
#      cmd: cat /etc/hostname
#  #    chdir: /opt
#  #- name: Print return information from the previous task
#  #  ansible.builtin.debug:
#  #    var: jump_host

- hosts: all
  gather_facts: true
  roles:
    - common

- hosts: nfs
  gather_facts: true
  roles:
    - nfs

- hosts: deployers
  gather_facts: true
  roles:
    - deployment-tools

- hosts: kubernetes
  gather_facts: true
  roles:
    - docker
    - kubernetes
    - deployment-tools

- hosts: kubemasters
  gather_facts: true
  roles:
    - kubemasters

- hosts: kubenodes
  gather_facts: true
  roles:
    - kubenodes

- hosts: deployers
  gather_facts: true
  roles:
    - ingress-nginx-controller