---
- hosts: all
  gather_facts: true
  roles:
    - common

- hosts: nfs
  gather_facts: true
  roles:
    - nfs

- hosts: deployer
  gather_facts: true
  roles:
    - deployment-tools

- hosts: kubernetes
  gather_facts: true
  roles:
    - docker
    - kubernetes

- hosts: kubemasters
  gather_facts: true
  roles:
    - kubemasters

- hosts: kubenodes
  gather_facts: true
  roles:
    - kubenodes

- hosts: deployer
  gather_facts: true
  roles:
    - ingress-nginx-controller
    - mysql
    - ghost